version: '3.8'

networks:
  kubernetes-env-manager:
    name:  kubernetes-env-manager


services:
  kubernetes-env-manager-backend:
    build:
      context: ./backend/
      args:
        - APP_VERSION
        - APP_DIR=backend
    image: ${REGISTRY}/kubernetes-env-manager-backend:${APP_VERSION}
    container_name: kubernetes-env-manager-backend
    volumes:
      - ./kubeconfig.yml:/opt/app/kubeconfig.yml
    env_file:
      - .env
    networks:
      kubernetes-env-manager:
        aliases:
          - rest_api
    ports:
      - "8080:80"
  kubernetes-env-manager-frontend:
    build:
      context: ./frontend/
      args:
        - APP_VERSION
    image: ${REGISTRY}/kubernetes-env-manager-frontend:${APP_VERSION}
    container_name: kubernetes-env-manager-frontend
    env_file:
      - .env
    ports:
      - '3000:80'
    networks:
      kubernetes-env-manager:
        aliases:
          - web