apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-env-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kube-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-env-account
  namespace: default
subjects:
- kind: ServiceAccount
  name: kube-env-account # Name of the ServiceAccount
  namespace: default
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: kube-role # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kube-backend
  name: kube-backend
spec:
  selector:
    matchLabels:
      io.kompose.service: kube-backend
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kube-backend
        app: kube-backend
        proj: kube-env-manager
    spec:
      serviceAccountName: kube-env-account
      containers:
      - image: 'registry.git.nosolutions.rs/vhire/vhire-backend/kubernetes-env-manager-backend:{{ .Values.app_version }}'
        name: kube-backend
        envFrom:
        - configMapRef:
            name: kube-env-config
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kube-backend
    app: kube-backend
  name: kube-backend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: kube-backend

